version: '3.4'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "dev"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  insuranceapi:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - sqlserver
    environment:
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=InsuranceDb;User Id=sa;Password=dev;"
    ports:
      - "8080:80"
